# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cpp_single_sample_expectation <- function(sampleReads, eHapsCurrent, nSNPs, N_r, calculate_updates = TRUE, calculate_read_probabilities = TRUE, t_break = 0L, t_reading_offset = 0L, t_writing_offset = 0L) {
    .Call('_SEW_cpp_single_sample_expectation', PACKAGE = 'SEW', sampleReads, eHapsCurrent, nSNPs, N_r, calculate_updates, calculate_read_probabilities, t_break, t_reading_offset, t_writing_offset)
}

